version: 0.2

env:
  variables:
    JEKYLL_ENV: "production"
    LC_CTYPE: "en_US.UTF-8"
  parameter-store:
    STG_BUCKET: "STG_BUCKET"
    PRD_BUCKET: "PRD_BUCKET"
phases:
  post_build:
    commands:
      - echo deploy to S3
      - aws s3 cp s3://$PRD_BUCKET/ s3://$STG_BUCKET/ --recursive

