version: 0.2

env:
  variables:
    JEKYLL_ENV: "staging"
    LC_CTYPE: "C.UTF-8"
  parameter-store:
    STG_BUCKET: "STG_BUCKET"
    PRD_BUCKET: "PRD_BUCKET"
phases:
  install:
    commands:
      - curl -Ls https://github.com/gohugoio/hugo/releases/download/v0.62/hugo_0.62_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/bin/hugo
  build:
    commands:
      - hugo --theme herring-cove
      - cp -a public/post/index.html public/
      - echo Build completed on `date`
  post_build:
    commands:
      - echo deploy to S3
      - aws s3 sync --exact-timestamps --delete public/ s3://$STG_BUCKET/
      - aws cloudfront create-invalidation --distribution-id E22457BCB27BR4 --paths '/*'
