version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "kter/blog"
  parameter-store:
    key: "value"
phases:
  install:
    commands:
      - echo install gcloud
      - apt-get update -y
      - apt-get install -y curl python
      - curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-170.0.1-linux-x86_64.tar.gz | tar zx
      - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
      - google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - google-cloud-sdk/bin/gcloud config set project personalprojects-189010
      - google-cloud-sdk/bin/gcloud --quiet config set container/cluster main-03
      - google-cloud-sdk/bin/gcloud config set compute/zone us-central1-a
      - google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials main-03
      - google-cloud-sdk/bin/gcloud --quiet components install kubectl
      - echo install jekyll
      # - apt-get install -y ruby-bundler
      - apt-get install -y libffi-dev build-base libxml2-dev libxslt-dev
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USER --password $DOCKER_PASS
      - echo setuup jekyll
      - bundle install --path vendor/bundle
  build:
    commands:
      - echo Build started on `date`
      - echo build html
      - bundle exec jekyll build
      - echo Build completed on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:`git rev-parse --short HEAD` .
      - docker tag $IMAGE_REPO_NAME:`git rev-parse --short HEAD` $IMAGE_REPO_NAME:`git rev-parse --short HEAD`
      - docker tag $IMAGE_REPO_NAME:`git rev-parse --short HEAD` $IMAGE_REPO_NAME:latest
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:`git rev-parse --short HEAD`
      - docker push $IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - echo deploy to kubernetes
      - google-cloud-sdk/bin/kubectl set image deployments/blog blog=$IMAGE_REPO_NAME:`git rev-parse --short HEAD`
      - google-cloud-sdk/bin/kubectl rollout status deployment/blog

