version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "kter/blog"
    JEKYLL_ENV: "production"
  parameter-store:
    DOCKER_EMAIL: "DOCKER_EMAIL"
    DOCKER_PASS: "DOCKER_PASS"
    DOCKER_USER: "DOCKER_USER"
    GCLOUD_SERVICE_KEY: "GCLOUD_SERVICE_KEY"
    GOOGLE_APPLICATION_CREDENTIALS: "GOOGLE_APPLICATION_CREDENTIALS"
phases:
  install:
    commands:
      - echo install gcloud
      - apt-get update -y
      - apt-get install -y curl python
      - curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-170.0.1-linux-x86_64.tar.gz | tar zx
      - echo $GCLOUD_SERVICE_KEY
      - echo $GCLOUD_SERVICE_KEY | base64 -d
      - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
      - google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - google-cloud-sdk/bin/gcloud config set project personalprojects-189010
      - google-cloud-sdk/bin/gcloud --quiet config set container/cluster main-03
      - google-cloud-sdk/bin/gcloud config set compute/zone us-central1-a
      - google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials main-03
      - google-cloud-sdk/bin/gcloud --quiet components install kubectl
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USER --password $DOCKER_PASS
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo deploy to kubernetes
      - google-cloud-sdk/bin/kubectl set image deployments/blog blog=$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - google-cloud-sdk/bin/kubectl rollout status deployment/blog

